Fir warnings
yedino/galaxy42 pull request #486
Opened 2018-02-12 11:40 UTC by sdf5

2018-02-13 02:15 UTC, rfreemobile commented
Please fix also the title in the commit itself, the commit still is "Fir...".

git -S --amend    and push again. Easy since it's just 1 commit.

2018-02-13 02:16 UTC, rfreemobile requested changes
just fix the title of commit with git -S --amend,
besides that seems ok

2018-02-13 13:30 UTC, neodr commented on src/test/utils_check.cpp
> +			too_big_map_by_size.insert(std::make_pair('a', std::array<long double, 100u>{0}));
in clang-4 is warning with this {0}

2018-03-05 15:55 UTC, rfree-d commented on src/tnetdbg.hpp
> +#define _throw_error_or_abort( EXCEPT ) do { auto except_var = (EXCEPT);  \
/***
 * This function tries to throw, BUT ALSO it is O.K. with possible ABORT, due to noexcept on the function we are in
 * it exists to e.g. silence some compilers warning about possible throw inside noexcept - we know, and we are o.k. with it turning into abort
 * use it in macros that should try to throw but abort if throwing is not possible
*/

2018-03-05 15:56 UTC, rfree-d commented on src/utils/check.hpp
>  /// err_check_prog?
// This macros can throw - BUT ALSO CAN ABORT - if used in noexcept function

2018-03-05 15:57 UTC, rfree-d commented on src/utils/privileges.cpp
> +		_check_abort(0); // trying to rethrow, will cause abort probably (if noexcept)
(false)

2018-03-05 15:58 UTC, rfree-d commented on src/utils/check.hpp
> +					_check_abort(0);
(false)

2018-03-05 15:58 UTC, rfree-d commented on src/utils/check.hpp
> +					_check_abort(0);
(false)

2018-03-05 15:59 UTC, rfree-d commented on src/test/utils_check.cpp
>  		}
^- this ident is ok (tabs versus spaces)?

we use tabs \t

@sdf5

2018-03-06 11:43 UTC, neodr approved these changes

2018-03-06 13:44 UTC, merged